set(TOOLCHAIN_TRIPLE aarch64-linux-gnu)
set(TOOLCHAIN_BASE_DIR /usr)
set(TOOLCHAIN_ROOTFS_DIR ${TOOLCHAIN_BASE_DIR}/${TOOLCHAIN_TRIPLE})

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSROOT "${TOOLCHAIN_ROOTFS_DIR}")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-psabi")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-psabi")

set(CMAKE_C_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-g++)

set(CMAKE_AR ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-gcc-ar)
set(CMAKE_AS ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-as)
set(CMAKE_NM ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-gcc-nm)
set(CMAKE_LINKER ${TOOLCHAIN_BASE_DIR}/bin/aarch64-linux-gnu-ld)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
